# frozen_string_literal: true

#
# FFX - Transpile Ruby FFI definitions into C extensions with ZJIT hints
#
# Usage in extconf.rb:
#
#   require_relative "ffx"
#   FFX.create_makefile("strlen", File.expand_path("strlen.rb", __dir__))
#
module FFX
  TYPES = {
    void:       { byte:  0, c_type: "void" },
    int:        { byte:  1, c_type: "int",                to_c: "NUM2INT(%s)",                   from_c: "INT2NUM(%s)" },
    long:       { byte:  2, c_type: "long",               to_c: "NUM2LONG(%s)",                  from_c: "LONG2NUM(%s)" },
    string:     { byte:  3, c_type: "const char *",       to_c: "StringValueCStr(%s)",           from_c: "rb_str_new_cstr(%s)" },
    uint:       { byte:  4, c_type: "unsigned int",       to_c: "NUM2UINT(%s)",                  from_c: "UINT2NUM(%s)" },
    size_t:     { byte:  5, c_type: "size_t",             to_c: "NUM2SIZET(%s)",                 from_c: "SIZET2NUM(%s)" },
    double:     { byte:  6, c_type: "double",             to_c: "NUM2DBL(%s)",                   from_c: "DBL2NUM(%s)" },
    float:      { byte:  7, c_type: "float",              to_c: "(float)NUM2DBL(%s)",            from_c: "DBL2NUM((double)%s)" },
    pointer:    { byte:  8, c_type: "void *",             to_c: "(void *)NUM2ULL(%s)",           from_c: "ULL2NUM((unsigned long long)%s)" },
    bool:       { byte:  9, c_type: "bool",               to_c: "(RTEST(%s) ? true : false)",    from_c: "((%s) ? Qtrue : Qfalse)" },
    char:       { byte: 10, c_type: "char",               to_c: "(char)NUM2INT(%s)",             from_c: "INT2NUM((int)%s)" },
    uchar:      { byte: 11, c_type: "unsigned char",      to_c: "(unsigned char)NUM2UINT(%s)",   from_c: "UINT2NUM((unsigned int)%s)" },
    short:      { byte: 12, c_type: "short",              to_c: "(short)NUM2INT(%s)",            from_c: "INT2NUM((int)%s)" },
    ushort:     { byte: 13, c_type: "unsigned short",     to_c: "(unsigned short)NUM2UINT(%s)",  from_c: "UINT2NUM((unsigned int)%s)" },
    int8:       { byte: 14, c_type: "int8_t",             to_c: "(int8_t)NUM2INT(%s)",           from_c: "INT2NUM((int)%s)" },
    uint8:      { byte: 15, c_type: "uint8_t",            to_c: "(uint8_t)NUM2UINT(%s)",         from_c: "UINT2NUM((unsigned int)%s)" },
    int16:      { byte: 16, c_type: "int16_t",            to_c: "(int16_t)NUM2INT(%s)",          from_c: "INT2NUM((int)%s)" },
    uint16:     { byte: 17, c_type: "uint16_t",           to_c: "(uint16_t)NUM2UINT(%s)",        from_c: "UINT2NUM((unsigned int)%s)" },
    int32:      { byte: 18, c_type: "int32_t",            to_c: "(int32_t)NUM2INT(%s)",          from_c: "INT2NUM((int)%s)" },
    uint32:     { byte: 19, c_type: "uint32_t",           to_c: "(uint32_t)NUM2UINT(%s)",        from_c: "UINT2NUM((unsigned int)%s)" },
    int64:      { byte: 20, c_type: "int64_t",            to_c: "(int64_t)NUM2LL(%s)",           from_c: "LL2NUM((long long)%s)" },
    uint64:     { byte: 21, c_type: "uint64_t",           to_c: "(uint64_t)NUM2ULL(%s)",         from_c: "ULL2NUM((unsigned long long)%s)" },
    long_long:  { byte: 22, c_type: "long long",          to_c: "NUM2LL(%s)",                    from_c: "LL2NUM(%s)" },
    ulong_long: { byte: 23, c_type: "unsigned long long", to_c: "NUM2ULL(%s)",                   from_c: "ULL2NUM(%s)" },
    ulong:      { byte: 24, c_type: "unsigned long",      to_c: "NUM2ULONG(%s)",                 from_c: "ULONG2NUM(%s)" },
  }

  @modules = {}

  module Library
    def self.extended(mod)
      FFX.register_module(mod)
    end

    def ffi_lib(*libs)
      FFX.module_data(self)[:libs].concat(libs.map(&:to_s))
    end

    def attach_function(name, params, ret)
      FFX.module_data(self)[:functions] << { name: name, params: params, ret: ret }
    end
  end

  class << self
    def register_module(mod)
      @modules[mod] = { libs: [], functions: [] }
    end

    def module_data(mod)
      @modules[mod]
    end

    def create_makefile(ext_name, source_file, headers: [])
      @modules = {}
      @headers = Array(headers)

      # Prepend the source directory so the empty ffi.rb stub there
      # shadows the real gem, keeping our FFI::Library recording stub intact
      ext_dir = File.expand_path(File.dirname(source_file))
      $LOAD_PATH.unshift(ext_dir)
      load File.expand_path(source_file)
      $LOAD_PATH.delete(ext_dir)

      if RUBY_ENGINE == "ruby"
        require "mkmf"

        # Write into $srcdir so the Makefile generated by mkmf (whose VPATH
        # points at $srcdir) always finds the source, regardless of whether
        # extconf.rb is being invoked in-place or from a build directory
        # like the one rake-compiler uses.
        File.write(File.join($srcdir, "#{ext_name}.c"), render(ext_name))

        @modules.each_value do |data|
          data[:functions].each do |f|
            abort "missing function: #{f[:name]}" unless have_func(f[:name].to_s, @headers)
          end
        end

        # Call mkmf's create_makefile (not ours)
        MakeMakefile.instance_method(:create_makefile).bind_call(self, ext_name)
      else
        write_rb_makefile(ext_name, source_file)
      end
    end

    private

    def write_rb_makefile(ext_name, source_file)
      require "rbconfig"
      srcdir = File.dirname(File.expand_path(source_file))
      src_basename = File.basename(source_file)

      File.write("Makefile", <<~MAKEFILE)
        SHELL = /bin/sh

        srcdir = #{srcdir}
        INSTALL_DATA = install -c -m 644
        MAKEDIRS = mkdir -p
        RM = rm -f

        target_prefix =
        sitelibdir = #{RbConfig::CONFIG["sitelibdir"]}
        RUBYLIBDIR = $(sitelibdir)$(target_prefix)

        all:

        install:
        \t$(MAKEDIRS) $(RUBYLIBDIR)
        \t$(INSTALL_DATA) $(srcdir)/#{src_basename} $(RUBYLIBDIR)/#{ext_name}.rb

        clean:

        distclean: clean
        \t-$(RM) Makefile

        .PHONY: all install clean distclean
      MAKEFILE
    end

    def render(ext_name)
      c = +"/* Generated by FFX - do not edit */\n"
      c << "#include <ruby.h>\n"
      c << "#include <string.h>\n"
      c << "#include <stdlib.h>\n"
      c << "#include <stdbool.h>\n"
      c << "#include <stdint.h>\n"
      c << "#include <math.h>\n"
      c << "#include <stdio.h>\n"
      Array(@headers).each { |h| c << "#include <#{h}>\n" }
      c << "\n"

      @modules.each do |mod, data|
        prefix = mod.name.gsub("::", "_").downcase
        data[:functions].each do |f|
          c << render_impl(f, prefix)
          c << render_trampoline(f, prefix)
        end
      end

      c << render_init(ext_name)
    end

    def vparams(f)
      (["VALUE self"] + f[:params].each_index.map { |i| "VALUE arg#{i}" }).join(", ")
    end

    def render_impl(f, prefix)
      name = f[:name]
      ret = f[:ret]
      impl = "rb_#{prefix}_#{name}_impl"

      args = f[:params].each_with_index.map { |t, i|
        TYPES.fetch(t)[:to_c] % "arg#{i}"
      }.join(", ")
      call = "#{name}(#{args})"

      body = if ret == :void
        "    #{call};\n    return Qnil;\n"
      else
        "    return #{TYPES.fetch(ret)[:from_c] % call};\n"
      end

      # Use asm label to force _ prefix on all platforms so the
      # trampoline can always branch to _impl without #ifdef
      out = +"static VALUE #{impl}(#{vparams(f)}) __asm__(\"_#{impl}\");\n\n"
      out << <<~C
        __attribute__((used))
        static VALUE
        #{impl}(#{vparams(f)})
        {
        #{body}}

      C
    end

    def render_trampoline(f, prefix)
      name = f[:name]
      params = f[:params]
      ret = f[:ret]
      wrapper = "rb_#{prefix}_#{name}_jit_wrapper"
      ptr_var  = "rb_#{prefix}_#{name}_fptr"

      c_ret    = TYPES.fetch(ret)[:c_type]
      c_params = params.empty? ? "void" :
        params.each_with_index.map { |t, i| "#{TYPES.fetch(t)[:c_type]} arg#{i}" }.join(", ")
      c_args   = params.each_index.map { |i| "arg#{i}" }.join(", ")
      wrapper_body = ret == :void ? "    #{name}(#{c_args});\n" :
                                    "    return #{name}(#{c_args});\n"

      pbytes = params.map { |t|
        "  \".byte #{TYPES.fetch(t)[:byte]}\\n\"\n"
      }.join

      <<~C
        static #{c_ret}
        #{wrapper}(#{c_params})
        {
            fprintf(stderr, "[ZJIT] FfiCall: #{name}\\n");
        #{wrapper_body}}

        /*
         * Storing the native function address directly would require a
         * relocation in read-only section .text, forcing DT_TEXTREL and making the
         * segment writable at load time. Instead we store an to a static variable;
         * ZJIT resolves the offset to get
         * the variable's address and dereferences it to obtain the function
         * pointer. Using a variable also lets us to use a consistent
         * underscore-prefixed name on all platforms
         */
        __attribute__((used))
        static void *#{ptr_var} __asm__("_#{ptr_var}") = (void *)#{wrapper};

        __attribute__((naked, aligned(16)))
        static VALUE
        rb_#{prefix}_#{name}(#{vparams(f)})
        {
        __asm__(
          "#{branch_mnemonic} _rb_#{prefix}_#{name}_impl\\n"
          ".long 0x46464930\\n"
          ".byte #{params.size}\\n"
        #{pbytes}  ".byte #{TYPES.fetch(ret)[:byte]}\\n"
          ".long _#{ptr_var} - .\\n"  /* PC-relative offset to ptr_var */
        );
        }

      C
    end

    def branch_mnemonic
      case RUBY_PLATFORM
      when /aarch64|arm64/ then "b"
      when /x86_64/        then "jmp"
      else raise "FFX: unsupported architecture: #{RUBY_PLATFORM}"
      end
    end

    def render_init(ext_name)
      out = +""
      out << "void\n"
      out << "Init_#{ext_name}(void)\n"
      out << "{\n"

      @modules.each do |mod, data|
        mn = mod.name
        prefix = mn.gsub("::", "_").downcase

        out << "    VALUE rb_m#{mn} = rb_define_module(\"#{mn}\");\n"

        data[:functions].each do |f|
          out << "    rb_define_module_function(rb_m#{mn}, \"#{f[:name]}\", rb_#{prefix}_#{f[:name]}, #{f[:params].size});\n"
          out << "    rb_define_module_function(rb_m#{mn}, \"#{f[:name]}_c\", rb_#{prefix}_#{f[:name]}_impl, #{f[:params].size});\n"
        end
      end

      out << "}\n"
    end
  end
end

module FFI
  Library = FFX::Library
end
